server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jdbc.lob.non_contextual_creation: true
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


